export const mockTasks = [
  {
    id: "task-1",
    title: "Daily Login Streak",
    description: "Login for 7 consecutive days to earn a special badge NFT",
    difficulty: "Easy",
    category: "Daily",
    timeEstimate: "5 minutes daily",
    reward: "Badge NFT",
    status: "available",
    requirements: [
      "Connect your wallet to the platform",
      "Login to the platform for 7 consecutive days",
      "Claim your reward on the 7th day",
    ],
  },
  {
    id: "task-2",
    title: "Community Challenge",
    description: "Participate in our Discord community event and submit proof of participation",
    difficulty: "Medium",
    category: "Community",
    timeEstimate: "1-2 hours",
    reward: "Community Spirit NFT",
    status: "available",
    requirements: [
      "Join our Discord server",
      "Participate in the weekly community event",
      "Submit a screenshot of your participation",
      "Get verified by a community moderator",
    ],
  },
  {
    id: "task-3",
    title: "Creative Contest",
    description: "Submit your original artwork based on this month's theme",
    difficulty: "Hard",
    category: "Creative",
    timeEstimate: "3-5 hours",
    reward: "Rare Artist NFT",
    status: "available",
    requirements: [
      "Create original artwork based on the theme: 'Digital Future'",
      "Artwork must be your own creation",
      "Submit in JPG or PNG format",
      "Include a brief description of your artwork",
    ],
  },
  {
    id: "task-4",
    title: "Social Media Promotion",
    description: "Share our platform on your social media and tag us",
    difficulty: "Easy",
    category: "Community",
    timeEstimate: "10 minutes",
    reward: "Promoter NFT",
    status: "available",
    requirements: [
      "Share our platform on Twitter, Instagram, or Facebook",
      "Tag our official account in your post",
      "Include the hashtag #QuestRewards",
      "Submit a screenshot of your post",
    ],
  },
  {
    id: "task-5",
    title: "Gaming Achievement",
    description: "Reach level 10 in our partner game and submit proof",
    difficulty: "Medium",
    category: "Gaming",
    timeEstimate: "2-3 hours",
    reward: "Gamer NFT",
    status: "available",
    requirements: [
      "Download and play our partner game",
      "Reach level 10 in the game",
      "Take a screenshot of your achievement",
      "Submit the screenshot as proof",
    ],
  },
  {
    id: "task-6",
    title: "Feedback Survey",
    description: "Complete our detailed platform feedback survey",
    difficulty: "Easy",
    category: "Daily",
    timeEstimate: "15 minutes",
    reward: "Contributor NFT",
    status: "completed",
    requirements: [
      "Complete all questions in the feedback survey",
      "Provide constructive feedback on your experience",
      "Submit the survey through the platform",
    ],
  },
]

export const mockNFTs = [
  {
    id: "nft-1",
    name: "Early Adopter Badge",
    description: "Awarded to early adopters of the QuestRewards platform",
    image: "/placeholder.svg?height=300&width=300",
    rarity: "Common",
    earnedDate: "2023-12-15",
  },
  {
    id: "nft-2",
    name: "Community Champion",
    description: "Recognizes outstanding contributions to the community",
    image: "/placeholder.svg?height=300&width=300",
    rarity: "Rare",
    earnedDate: "2024-01-20",
  },
  {
    id: "nft-3",
    name: "Creative Genius",
    description: "Awarded for exceptional creativity in the monthly art contest",
    image: "/placeholder.svg?height=300&width=300",
    rarity: "Epic",
    earnedDate: "2024-02-05",
  },
  {
    id: "nft-4",
    name: "Social Butterfly",
    description: "Earned by promoting QuestRewards across social media platforms",
    image: "/placeholder.svg?height=300&width=300",
    rarity: "Uncommon",
    earnedDate: "2024-02-28",
  },
]
